import { Recipe, Ingredient } from "../types/Recipe";

/**
 * Seed data - Initial 50 recipes with full, realistic content.
 *
 * Each recipe carries hand-written ingredients (with realistic per-ingredient
 * costs) and real cooking instructions. The displayed `cost` field is derived
 * from the ingredient costs so what you see equals what the grocery list will
 * sum to.
 */

// ---------------------------------------------------------------------------
// Image library
// ---------------------------------------------------------------------------
const IMG = {
  eggSandwich: "https://images.unsplash.com/photo-1687102624999-2615998b3ee5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlZ2clMjBzYW5kd2ljaHxlbnwxfHx8fDE3Nzg1ODY1ODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  chickenRice: "https://images.unsplash.com/photo-1636401870585-a8852371e84a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwcmljZSUyMGJvd2x8ZW58MXx8fHwxNzc4NzAwMTI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
  tofuStirFry: "https://images.unsplash.com/photo-1619683548293-c74defe8d5d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2Z1JTIwc3RpciUyMGZyeXxlbnwxfHx8fDE3Nzg3MDAxMjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
  pestoPasta: "https://images.unsplash.com/photo-1616299908398-9af1134ad522?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXN0byUyMHBhc3RhfGVufDF8fHx8MTc3ODcwMDEyOHww&ixlib=rb-4.1.0&q=80&w=1080",
  ramen: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYW1lbnxlbnwxfHx8fDE3Nzg3MDAxMjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
  turkeyWrap: "https://images.unsplash.com/photo-1763891538128-cdad95beb521?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjB3cmFwfGVufDF8fHx8MTc3ODcwMDEyOHww&ixlib=rb-4.1.0&q=80&w=1080",
  yogurtBowl: "https://images.unsplash.com/photo-1641494587136-eec74f1944ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmVlayUyMHlvZ3VydCUyMGJvd2x8ZW58MXx8fHwxNzc4NzAwMTI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
  salmonBowl: "https://images.unsplash.com/photo-1638502182261-7be714a565ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjByaWNlJTIwYm93bHxlbnwxfHx8fDE3Nzg3MDAxMjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
  beanQuesadilla: "https://images.unsplash.com/photo-1584398572810-43c36faba2ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMGJlYW4lMjBxdWVzYWRpbGxhfGVufDF8fHx8MTc3ODcwMDEyOHww&ixlib=rb-4.1.0&q=80&w=1080",
  overnightOats: "https://images.unsplash.com/photo-1490371475955-4cb3bfc72f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdmVybmlnaHQlMjBvYXRzfGVufDF8fHx8MTc3ODcwMDEyOHww&ixlib=rb-4.1.0&q=80&w=1080",
  peanutNoodles: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTcGljeSUyMFBlYW51dCUyME5vb2RsZXN8ZW58MXx8fHwxNzc4ODIwNTIyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  capreseSandwich: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDYXByZXNlJTIwU2FuZHdpY2h8ZW58MXx8fHwxNzc4ODIwNTIyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  beefTacos: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCZWVmJTIwVGFjb3N8ZW58MXx8fHwxNzc4ODIwNTIyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  lentilSoup: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxMZW50aWwlMjBTb3VwfGVufDF8fHx8MTc3ODgyMDUyMnww&ixlib=rb-4.1.0&q=80&w=1080",
  bbqWrap: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCQlElMjBDaGlja2VuJTIwV3JhcHxlbnwxfHx8fDE3Nzg4MjA1MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  mushroomRisotto: "https://images.unsplash.com/photo-1609770424775-39ec362f2d94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNdXNocm9vbSUyMFJpc290dG98ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  hummusPita: "https://images.unsplash.com/photo-1603133872497-f29809b750bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIdW1tdXMlMjBQaXRhJTIwUGxhdGV8ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  shrimpFriedRice: "https://images.unsplash.com/photo-1609570324378-ec0c4c9b6ba8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTaHJpbXAlMjBGcmllZCUyMFJpY2V8ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  macAndCheese: "https://images.unsplash.com/photo-1667499989723-c4ab9549d63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNYWMlMjBhbmQlMjBDaGVlc2V8ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  avocadoToast: "https://images.unsplash.com/photo-1687276287139-88f7333c8ca4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxBdm9jYWRvJTIwVG9hc3R8ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  tunaSandwich: "https://images.unsplash.com/photo-1558985250-27a406d64cb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUdW5hJTIwU2FsYWQlMjBTYW5kd2ljaHxlbnwxfHx8fDE3Nzg4MjA1MjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
  breakfastBurrito: "https://images.unsplash.com/photo-1711488735428-27c6757beb5c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCcmVha2Zhc3QlMjBCdXJyaXRvfGVufDF8fHx8MTc3ODgyMDUyNHww&ixlib=rb-4.1.0&q=80&w=1080",
  chickenParm: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwUGFybWVzYW58ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  veggieBurger: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxWZWdnaWUlMjBCdXJnZXJ8ZW58MXx8fHwxNzc4ODIwNTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
  teriyakiSalmon: "https://images.unsplash.com/photo-1684815595429-cf46bff6294f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUZXJpeWFraSUyMFNhbG1vbnxlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  pancakes: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQYW5jYWtlc3xlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  frenchToast: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxGcmVuY2glMjBUb2FzdHxlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  chickenQuesadilla: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwUXVlc2FkaWxsYXxlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  sweetPotatoBowl: "https://images.unsplash.com/photo-1603481712606-08b5a2789816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTd2VldCUyMFBvdGF0byUyMEJvd2x8ZW58MXx8fHwxNzc4ODIwNTI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  falafelWrap: "https://images.unsplash.com/photo-1681072530653-db8fe2538631?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxGYWxhZmVsJTIwV3JhcHxlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  pastaPrimavera: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQYXN0YSUyMFByaW1hdmVyYXxlbnwxfHx8fDE3Nzg4MjA1MjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
  porkChops: "https://images.unsplash.com/photo-1611059263765-f57653f3bba3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQb3JrJTIwQ2hvcHN8ZW58MXx8fHwxNzc4ODIwNTI1fDA&ixlib=rb-4.1.0&q=80&w=1080",
  caesarSalad: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQ2Flc2FyJTIwU2FsYWR8ZW58MXx8fHwxNzc4ODIwNTI1fDA&ixlib=rb-4.1.0&q=80&w=1080",
  steakFajitas: "https://images.unsplash.com/photo-1624234734133-7f1342047e30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTdGVhayUyMEZhaml0YXN8ZW58MXx8fHwxNzc4ODIwNTI1fDA&ixlib=rb-4.1.0&q=80&w=1080",
  vegCurry: "https://images.unsplash.com/photo-1596797038530-2c107229654b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxWZWdldGFibGUlMjBDdXJyeXxlbnwxfHx8fDE3Nzg4MjA1MjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
  tomatoSoup: "https://images.unsplash.com/photo-1629978444632-9f63ba0eff47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUb21hdG8lMjBCYXNpbCUyMFNvdXB8ZW58MXx8fHwxNzc4ODIwNTI1fDA&ixlib=rb-4.1.0&q=80&w=1080",
  grilledCheese: "https://images.unsplash.com/photo-1528736235302-52922df5c122?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxHcmlsbGVkJTIwQ2hlZXNlfGVufDF8fHx8MTc3ODgyMDUyNXww&ixlib=rb-4.1.0&q=80&w=1080",
  eggplantParm: "https://images.unsplash.com/photo-1632229095740-8c75082087c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxFZ2dwbGFudCUyMFBhcm1lc2FufGVufDF8fHx8MTc3ODgyMDUyNnww&ixlib=rb-4.1.0&q=80&w=1080",
  tikkaMasala: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwVGlra2ElMjBNYXNhbGF8ZW58MXx8fHwxNzc4ODIwNTI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  beefStirFry: "https://images.unsplash.com/photo-1600180786608-28d06391d25c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCZWVmJTIwU3RpciUyMEZyeXxlbnwxfHx8fDE3Nzg4MjA1MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  shrimpScampi: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTaHJpbXAlMjBTY2FtcGl8ZW58MXx8fHwxNzc4ODIwNTI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  bakedZiti: "https://images.unsplash.com/photo-1612152328178-4a6c83d96429?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCYWtlZCUyMFppdGl8ZW58MXx8fHwxNzc4ODIwNTI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  chickenNoodleSoup: "https://images.unsplash.com/photo-1470324161839-ce2bb6fa6bc3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwTm9vZGxlJTIwU291cHxlbnwxfHx8fDE3Nzg4MjA1MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  spinachQuiche: "https://images.unsplash.com/photo-1612477491914-a2f46ef8586e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTcGluYWNoJTIwUXVpY2hlfGVufDF8fHx8MTc3ODgyMDUyNnww&ixlib=rb-4.1.0&q=80&w=1080",
  stuffedPeppers: "https://images.unsplash.com/photo-1673646960062-9aeb2188335f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTdHVmZmVkJTIwQmVsbCUyMFBlcHBlcnN8ZW58MXx8fHwxNzc4ODIwNTI2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  chickenFajitaBowl: "https://images.unsplash.com/photo-1668665771757-4d42737d295a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwRmFqaXRhJTIwQm93bHxlbnwxfHx8fDE3Nzg4MjA1MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  tofuScramble: "https://images.unsplash.com/photo-1563690449029-d6e1b8d6003d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUb2Z1JTIwU2NyYW1ibGV8ZW58MXx8fHwxNzc4ODIwNTI3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  fishTacos: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxGaXNoJTIwVGFjb3N8ZW58MXx8fHwxNzc4ODIwNTI3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  beefStew: "https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCZWVmJTIwU3Rld3xlbnwxfHx8fDE3Nzg4MjA1Mjd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  chickenAlfredo: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQWxmcmVkb3xlbnwxfHx8fDE3Nzg4MjA1Mjd8MA&ixlib=rb-4.1.0&q=80&w=1080",
};

// ---------------------------------------------------------------------------
// Helper to total ingredient cost into the "$X.XX" string the UI expects
// ---------------------------------------------------------------------------
function totalCost(ingredients: Ingredient[]): string {
  const sum = ingredients.reduce((acc, ing) => acc + (ing.optional ? 0 : ing.cost), 0);
  return "$" + sum.toFixed(2);
}

type RecipeSeed = Omit<Recipe, "cost" | "createdAt" | "updatedAt" | "source" | "isPublic" | "timesCooked">;

const SEEDS: RecipeSeed[] = [
  {
    id: "1",
    name: "Chicken Rice Bowl",
    image: IMG.chickenRice,
    description: "A hearty bowl of seasoned chicken, fluffy rice, and steamed broccoli.",
    prepTime: "20 min",
    cookTime: "15 min",
    tags: ["high protein", "quick", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 1,
    calories: 520,
    ingredients: [
      { name: "Chicken breast", category: "protein", quantity: "1 piece (6 oz)", cost: 2.50 },
      { name: "White rice", category: "grains", quantity: "1 cup cooked", cost: 0.50 },
      { name: "Broccoli florets", category: "produce", quantity: "1 cup", cost: 1.00 },
      { name: "Soy sauce", category: "pantry", quantity: "2 tbsp", cost: 0.20 },
      { name: "Olive oil", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
      { name: "Garlic", category: "produce", quantity: "2 cloves, minced", cost: 0.10 },
    ],
    steps: [
      "Rinse rice and cook according to package directions (about 15 min).",
      "Pat chicken dry, season with salt and pepper, then cut into 1-inch pieces.",
      "Heat olive oil in a skillet over medium-high heat. Add garlic, cook 30 seconds.",
      "Add chicken and cook 6-8 minutes, stirring, until browned and cooked through (165°F).",
      "Steam broccoli in a covered pan with 2 tbsp water for 4 minutes until bright green.",
      "Plate rice, top with chicken and broccoli, then drizzle with soy sauce.",
    ],
  },
  {
    id: "2",
    name: "Pesto Pasta",
    image: IMG.pestoPasta,
    description: "Classic Italian pasta tossed in vibrant basil pesto with parmesan.",
    prepTime: "15 min",
    cookTime: "10 min",
    tags: ["vegetarian", "comfort food", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 450,
    ingredients: [
      { name: "Pasta (penne or fusilli)", category: "grains", quantity: "200 g", cost: 1.00 },
      { name: "Basil pesto", category: "pantry", quantity: "3 tbsp", cost: 1.50 },
      { name: "Parmesan", category: "dairy", quantity: "2 tbsp grated", cost: 0.75 },
      { name: "Cherry tomatoes", category: "produce", quantity: "1/2 cup, halved", cost: 0.75 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
      { name: "Salt & pepper", category: "spices", quantity: "to taste", cost: 0.05 },
    ],
    steps: [
      "Bring a large pot of salted water to a rolling boil.",
      "Add pasta and cook until al dente (about 8-10 min). Reserve 1/4 cup pasta water before draining.",
      "Return drained pasta to the pot. Add pesto and a splash of pasta water; toss until creamy.",
      "Stir in halved cherry tomatoes and olive oil.",
      "Plate and finish with grated parmesan and freshly cracked pepper.",
    ],
  },
  {
    id: "3",
    name: "Egg Sandwich",
    image: IMG.eggSandwich,
    description: "Quick toasted sandwich with melted cheese and fluffy eggs.",
    prepTime: "5 min",
    cookTime: "5 min",
    tags: ["quick", "cheap", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 1,
    calories: 320,
    ingredients: [
      { name: "Eggs", category: "protein", quantity: "2 large", cost: 0.60 },
      { name: "Sandwich bread", category: "grains", quantity: "2 slices", cost: 0.50 },
      { name: "American cheese", category: "dairy", quantity: "1 slice", cost: 0.50 },
      { name: "Butter", category: "dairy", quantity: "1 tsp", cost: 0.10 },
      { name: "Salt & pepper", category: "spices", quantity: "to taste", cost: 0.05 },
    ],
    steps: [
      "Crack eggs into a bowl, whisk with salt and pepper.",
      "Melt butter in a small non-stick pan over medium heat.",
      "Pour in eggs; gently fold until soft curds form, about 2 minutes.",
      "Toast bread until golden brown.",
      "Lay cheese on one slice, top with eggs while still hot so cheese melts, close sandwich and serve.",
    ],
  },
  {
    id: "4",
    name: "Tofu Stir Fry",
    image: IMG.tofuStirFry,
    description: "Crispy tofu with colorful veggies in a glossy teriyaki glaze.",
    prepTime: "20 min",
    cookTime: "10 min",
    tags: ["vegan", "healthy", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 380,
    ingredients: [
      { name: "Firm tofu", category: "protein", quantity: "1 block (14 oz)", cost: 2.50 },
      { name: "Stir-fry vegetable mix", category: "produce", quantity: "2 cups", cost: 2.00 },
      { name: "Teriyaki sauce", category: "pantry", quantity: "3 tbsp", cost: 0.50 },
      { name: "Sesame oil", category: "pantry", quantity: "1 tbsp", cost: 0.25 },
      { name: "Garlic", category: "produce", quantity: "2 cloves", cost: 0.10 },
      { name: "Sesame seeds", category: "pantry", quantity: "1 tsp", cost: 0.15 },
    ],
    steps: [
      "Drain tofu and press between paper towels under a heavy plate for 15 minutes to remove water.",
      "Cube tofu into 1-inch pieces.",
      "Heat sesame oil in a wok or large skillet over medium-high heat. Add tofu in a single layer.",
      "Cook tofu undisturbed 3 minutes per side, until each side is crispy and golden.",
      "Push tofu to the side, add garlic and vegetables; stir-fry 4-5 minutes until tender-crisp.",
      "Pour in teriyaki sauce and toss everything until coated. Garnish with sesame seeds.",
    ],
  },
  {
    id: "5",
    name: "Turkey Wrap",
    image: IMG.turkeyWrap,
    description: "A no-cook lunch wrap with deli turkey, fresh greens, and mayo.",
    prepTime: "5 min",
    tags: ["quick", "lunch", "easy prep"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 290,
    ingredients: [
      { name: "Flour tortilla (large)", category: "grains", quantity: "1", cost: 0.50 },
      { name: "Sliced deli turkey", category: "protein", quantity: "4 slices", cost: 2.00 },
      { name: "Romaine lettuce", category: "produce", quantity: "1 handful", cost: 0.50 },
      { name: "Tomato", category: "produce", quantity: "3 slices", cost: 0.40 },
      { name: "Mayonnaise", category: "pantry", quantity: "1 tbsp", cost: 0.15 },
      { name: "Dijon mustard", category: "pantry", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Lay the tortilla flat on a cutting board.",
      "Spread mayo and mustard across the center.",
      "Layer turkey, lettuce, and tomato in the lower third of the tortilla.",
      "Fold the sides in, then roll tightly from the bottom up.",
      "Slice in half on the diagonal and serve.",
    ],
  },
  {
    id: "6",
    name: "Ramen With Vegetables",
    image: IMG.ramen,
    description: "A loaded bowl of brothy ramen with mushrooms, bok choy, and a soft egg.",
    prepTime: "5 min",
    cookTime: "15 min",
    tags: ["comfort food", "quick", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 1,
    calories: 480,
    ingredients: [
      { name: "Ramen noodles", category: "grains", quantity: "1 packet", cost: 1.00 },
      { name: "Egg", category: "protein", quantity: "1 large", cost: 0.30 },
      { name: "Baby bok choy", category: "produce", quantity: "2 heads", cost: 1.25 },
      { name: "Shiitake mushrooms", category: "produce", quantity: "1/2 cup sliced", cost: 1.00 },
      { name: "Green onion", category: "produce", quantity: "1, sliced", cost: 0.20 },
      { name: "Soy sauce", category: "pantry", quantity: "1 tbsp", cost: 0.10 },
      { name: "Sesame oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Bring 2 cups of water to a gentle boil in a saucepan.",
      "Lower the egg in carefully; cook 6 1/2 minutes for jammy yolk, then transfer to ice water.",
      "In the same water, add mushrooms and the soup base from the ramen packet. Simmer 3 minutes.",
      "Add noodles and bok choy; cook 3 more minutes.",
      "Pour into a bowl, drizzle with soy sauce and sesame oil.",
      "Peel and halve the egg, place on top with green onion.",
    ],
  },
  {
    id: "7",
    name: "Greek Yogurt Bowl",
    image: IMG.yogurtBowl,
    description: "Creamy Greek yogurt topped with berries, granola, and honey.",
    prepTime: "5 min",
    tags: ["healthy", "quick", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 1,
    calories: 340,
    ingredients: [
      { name: "Greek yogurt (plain)", category: "dairy", quantity: "1 cup", cost: 1.25 },
      { name: "Granola", category: "grains", quantity: "1/4 cup", cost: 0.75 },
      { name: "Mixed berries", category: "produce", quantity: "1/2 cup", cost: 1.25 },
      { name: "Honey", category: "pantry", quantity: "1 tbsp", cost: 0.30 },
      { name: "Chia seeds", category: "pantry", quantity: "1 tsp", cost: 0.15, optional: true },
    ],
    steps: [
      "Spoon yogurt into a wide bowl.",
      "Top with berries on one side and granola on the other.",
      "Drizzle with honey and sprinkle chia seeds if using.",
      "Serve immediately so granola stays crunchy.",
    ],
  },
  {
    id: "8",
    name: "Salmon Rice Bowl",
    image: IMG.salmonBowl,
    description: "Flaky baked salmon over jasmine rice with avocado and cucumber.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["high protein", "healthy", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 1,
    calories: 590,
    ingredients: [
      { name: "Salmon fillet", category: "protein", quantity: "5 oz", cost: 4.50 },
      { name: "Jasmine rice", category: "grains", quantity: "1 cup cooked", cost: 0.60 },
      { name: "Avocado", category: "produce", quantity: "1/2", cost: 0.85 },
      { name: "Cucumber", category: "produce", quantity: "1/2, sliced", cost: 0.50 },
      { name: "Soy sauce", category: "pantry", quantity: "1 tbsp", cost: 0.10 },
      { name: "Sriracha or chili crisp", category: "pantry", quantity: "1 tsp", cost: 0.10 },
      { name: "Sesame seeds", category: "pantry", quantity: "1 tsp", cost: 0.15 },
    ],
    steps: [
      "Preheat oven to 400°F (200°C). Line a sheet pan with parchment.",
      "Place salmon skin-side down, brush with a little soy sauce, and bake 12-14 min until it flakes.",
      "While salmon bakes, cook rice if not already done.",
      "Slice cucumber and avocado.",
      "Build the bowl: rice on the bottom, then salmon, avocado, and cucumber arranged around.",
      "Drizzle with sriracha and sprinkle sesame seeds.",
    ],
  },
  {
    id: "9",
    name: "Black Bean Quesadilla",
    image: IMG.beanQuesadilla,
    description: "Crispy tortilla packed with seasoned black beans, cheese, and salsa.",
    prepTime: "5 min",
    cookTime: "8 min",
    tags: ["vegetarian", "quick", "lunch"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 460,
    ingredients: [
      { name: "Flour tortilla", category: "grains", quantity: "1 large", cost: 0.50 },
      { name: "Canned black beans", category: "pantry", quantity: "1/2 cup, drained", cost: 0.75 },
      { name: "Shredded cheddar/jack", category: "dairy", quantity: "1/2 cup", cost: 1.25 },
      { name: "Salsa", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Cumin", category: "spices", quantity: "1/4 tsp", cost: 0.05 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Lightly mash beans with cumin and a pinch of salt.",
      "Heat olive oil in a skillet over medium heat.",
      "Place tortilla in the pan, sprinkle cheese on one half, top with beans and salsa.",
      "Fold tortilla in half, press gently. Cook 2-3 minutes until golden.",
      "Flip carefully and cook another 2-3 minutes until cheese is fully melted.",
      "Transfer to a board, slice into wedges, and serve with extra salsa.",
    ],
  },
  {
    id: "10",
    name: "Overnight Oats",
    image: IMG.overnightOats,
    description: "Make-ahead oats soaked in milk with banana, peanut butter, and honey.",
    prepTime: "5 min",
    tags: ["healthy", "easy prep", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 1,
    calories: 410,
    ingredients: [
      { name: "Rolled oats", category: "grains", quantity: "1/2 cup", cost: 0.30 },
      { name: "Milk (or oat milk)", category: "dairy", quantity: "3/4 cup", cost: 0.50 },
      { name: "Banana", category: "produce", quantity: "1, sliced", cost: 0.30 },
      { name: "Peanut butter", category: "pantry", quantity: "1 tbsp", cost: 0.25 },
      { name: "Honey", category: "pantry", quantity: "1 tsp", cost: 0.10 },
      { name: "Chia seeds", category: "pantry", quantity: "1 tsp", cost: 0.15, optional: true },
    ],
    steps: [
      "Combine oats, milk, peanut butter, and honey in a jar; stir well.",
      "Stir in chia seeds if using.",
      "Seal and refrigerate at least 4 hours, ideally overnight.",
      "In the morning, top with banana slices and a small swirl of extra peanut butter.",
    ],
  },
  {
    id: "11",
    name: "Spicy Peanut Noodles",
    image: IMG.peanutNoodles,
    description: "Slurpable noodles in a creamy, spicy peanut sauce.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["vegan", "quick", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 510,
    ingredients: [
      { name: "Spaghetti or rice noodles", category: "grains", quantity: "200 g", cost: 1.00 },
      { name: "Peanut butter", category: "pantry", quantity: "1/4 cup", cost: 0.60 },
      { name: "Soy sauce", category: "pantry", quantity: "2 tbsp", cost: 0.20 },
      { name: "Rice vinegar", category: "pantry", quantity: "1 tbsp", cost: 0.15 },
      { name: "Sriracha", category: "pantry", quantity: "1 tbsp", cost: 0.15 },
      { name: "Garlic", category: "produce", quantity: "2 cloves", cost: 0.10 },
      { name: "Green onion", category: "produce", quantity: "2, sliced", cost: 0.40 },
      { name: "Crushed peanuts", category: "pantry", quantity: "2 tbsp", cost: 0.30, optional: true },
    ],
    steps: [
      "Cook noodles in salted boiling water until just tender. Reserve 1/4 cup cooking water.",
      "While noodles cook, whisk peanut butter, soy sauce, rice vinegar, sriracha, and minced garlic.",
      "Thin sauce with 2-3 tbsp pasta water until pourable.",
      "Drain noodles and toss with sauce until evenly coated.",
      "Top with green onions and crushed peanuts.",
    ],
  },
  {
    id: "12",
    name: "Caprese Sandwich",
    image: IMG.capreseSandwich,
    description: "Crusty ciabatta layered with mozzarella, tomato, basil, and balsamic.",
    prepTime: "10 min",
    tags: ["vegetarian", "lunch", "fresh"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 420,
    ingredients: [
      { name: "Ciabatta roll", category: "grains", quantity: "1", cost: 1.00 },
      { name: "Fresh mozzarella", category: "dairy", quantity: "3 oz, sliced", cost: 2.00 },
      { name: "Tomato", category: "produce", quantity: "1, sliced", cost: 0.75 },
      { name: "Fresh basil leaves", category: "produce", quantity: "6", cost: 0.50 },
      { name: "Balsamic glaze", category: "pantry", quantity: "1 tbsp", cost: 0.25 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Split ciabatta and lightly toast in a dry pan or toaster oven.",
      "Drizzle bottom half with olive oil.",
      "Layer mozzarella, tomato slices, and basil leaves.",
      "Season with salt and pepper, drizzle balsamic glaze over the top.",
      "Close sandwich, press gently, and slice in half.",
    ],
  },
  {
    id: "13",
    name: "Beef Tacos",
    image: IMG.beefTacos,
    description: "Seasoned ground beef in warm tortillas with crisp toppings.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["high protein", "dinner", "family"],
    difficulty: "Easy",
    category: "dinner",
    servings: 3,
    calories: 540,
    ingredients: [
      { name: "Ground beef (80/20)", category: "protein", quantity: "1 lb", cost: 5.50 },
      { name: "Taco seasoning", category: "spices", quantity: "1 packet", cost: 1.00 },
      { name: "Corn tortillas", category: "grains", quantity: "6", cost: 1.00 },
      { name: "Shredded lettuce", category: "produce", quantity: "1 cup", cost: 0.75 },
      { name: "Tomato", category: "produce", quantity: "1, diced", cost: 0.75 },
      { name: "Shredded cheese", category: "dairy", quantity: "1/2 cup", cost: 1.25 },
      { name: "Sour cream", category: "dairy", quantity: "1/4 cup", cost: 0.50, optional: true },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat, breaking it up, about 6-7 minutes.",
      "Drain excess fat. Stir in taco seasoning and 1/2 cup water; simmer 3-4 minutes until thickened.",
      "Warm tortillas in a dry skillet or microwave wrapped in a damp towel.",
      "Spoon beef into each tortilla.",
      "Top with lettuce, tomato, cheese, and sour cream.",
    ],
  },
  {
    id: "14",
    name: "Lentil Soup",
    image: IMG.lentilSoup,
    description: "Cozy spiced lentil soup with carrots, celery, and tomato.",
    prepTime: "10 min",
    cookTime: "30 min",
    tags: ["vegan", "healthy", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 4,
    calories: 320,
    ingredients: [
      { name: "Dried green lentils", category: "pantry", quantity: "1 cup", cost: 1.25 },
      { name: "Yellow onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Carrots", category: "produce", quantity: "2, diced", cost: 0.50 },
      { name: "Celery", category: "produce", quantity: "2 stalks, diced", cost: 0.50 },
      { name: "Canned diced tomatoes", category: "pantry", quantity: "1 can (14 oz)", cost: 1.25 },
      { name: "Vegetable broth", category: "pantry", quantity: "4 cups", cost: 1.50 },
      { name: "Cumin", category: "spices", quantity: "1 tsp", cost: 0.10 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Heat olive oil in a pot over medium heat.",
      "Sauté onion, carrot, and celery until softened, about 6 minutes.",
      "Stir in cumin and cook 30 seconds until fragrant.",
      "Add lentils, diced tomatoes, and broth. Bring to a boil.",
      "Reduce heat and simmer 25-30 min, stirring occasionally, until lentils are tender.",
      "Season with salt and pepper. For a creamier soup, blend half and stir it back in.",
    ],
  },
  {
    id: "15",
    name: "BBQ Chicken Wrap",
    image: IMG.bbqWrap,
    description: "Smoky pulled chicken with crunchy slaw in a soft tortilla.",
    prepTime: "5 min",
    cookTime: "5 min",
    tags: ["quick", "lunch", "high protein"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 510,
    ingredients: [
      { name: "Cooked rotisserie chicken (shredded)", category: "protein", quantity: "1 cup", cost: 3.00 },
      { name: "BBQ sauce", category: "pantry", quantity: "3 tbsp", cost: 0.30 },
      { name: "Coleslaw mix", category: "produce", quantity: "1/2 cup", cost: 0.75 },
      { name: "Flour tortilla (large)", category: "grains", quantity: "1", cost: 0.50 },
      { name: "Shredded cheddar", category: "dairy", quantity: "1/4 cup", cost: 0.60 },
      { name: "Ranch dressing", category: "pantry", quantity: "1 tbsp", cost: 0.15 },
    ],
    steps: [
      "In a small bowl, toss shredded chicken with BBQ sauce until coated.",
      "In another bowl, mix coleslaw with ranch dressing.",
      "Warm tortilla in a dry skillet 30 seconds per side.",
      "Lay chicken across the center of the tortilla; top with slaw and cheddar.",
      "Fold sides in and roll tightly. Slice in half on the diagonal.",
    ],
  },
  {
    id: "16",
    name: "Mushroom Risotto",
    image: IMG.mushroomRisotto,
    description: "Creamy arborio rice slow-cooked with mushrooms and parmesan.",
    prepTime: "10 min",
    cookTime: "30 min",
    tags: ["vegetarian", "comfort food", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 540,
    ingredients: [
      { name: "Arborio rice", category: "grains", quantity: "1 cup", cost: 1.50 },
      { name: "Cremini mushrooms", category: "produce", quantity: "8 oz, sliced", cost: 2.50 },
      { name: "Vegetable broth", category: "pantry", quantity: "4 cups, warmed", cost: 1.50 },
      { name: "Yellow onion", category: "produce", quantity: "1/2, diced", cost: 0.25 },
      { name: "Garlic", category: "produce", quantity: "2 cloves", cost: 0.10 },
      { name: "Parmesan", category: "dairy", quantity: "1/4 cup grated", cost: 1.00 },
      { name: "Butter", category: "dairy", quantity: "2 tbsp", cost: 0.30 },
      { name: "White wine", category: "pantry", quantity: "1/4 cup", cost: 0.50, optional: true },
    ],
    steps: [
      "Warm broth in a small saucepan; keep at a low simmer.",
      "Melt 1 tbsp butter in a wide pan, sauté mushrooms until browned. Remove and set aside.",
      "Add remaining butter, cook onion 3 min until translucent. Add garlic for 30 seconds.",
      "Stir in rice; toast 1-2 min until edges look translucent. Add wine and stir until absorbed.",
      "Add broth one ladle at a time, stirring constantly until each addition is absorbed (20-25 min total).",
      "Stir in mushrooms and parmesan; season with salt and pepper.",
    ],
  },
  {
    id: "17",
    name: "Hummus & Pita Plate",
    image: IMG.hummusPita,
    description: "Mediterranean platter with hummus, pita, cucumber, and olives.",
    prepTime: "10 min",
    tags: ["vegetarian", "fresh", "lunch"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 480,
    ingredients: [
      { name: "Hummus", category: "pantry", quantity: "1/2 cup", cost: 1.50 },
      { name: "Pita bread", category: "grains", quantity: "1 large, cut into wedges", cost: 0.75 },
      { name: "Cucumber", category: "produce", quantity: "1, sliced", cost: 0.75 },
      { name: "Cherry tomatoes", category: "produce", quantity: "1/2 cup", cost: 0.75 },
      { name: "Kalamata olives", category: "pantry", quantity: "1/4 cup", cost: 1.00 },
      { name: "Feta cheese", category: "dairy", quantity: "2 tbsp crumbled", cost: 0.75 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Spread hummus on a plate, using the back of a spoon to make a swirl.",
      "Drizzle with olive oil and a pinch of paprika or za'atar if you have it.",
      "Arrange cucumber, cherry tomatoes, olives, and pita wedges around the hummus.",
      "Crumble feta over the top and serve.",
    ],
  },
  {
    id: "18",
    name: "Shrimp Fried Rice",
    image: IMG.shrimpFriedRice,
    description: "Day-old rice tossed in a hot wok with shrimp, peas, and egg.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["high protein", "quick", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 510,
    ingredients: [
      { name: "Cooked rice (day-old)", category: "grains", quantity: "2 cups", cost: 1.00 },
      { name: "Shrimp (peeled, deveined)", category: "protein", quantity: "1/2 lb", cost: 4.50 },
      { name: "Eggs", category: "protein", quantity: "2", cost: 0.60 },
      { name: "Frozen peas & carrots", category: "produce", quantity: "1 cup", cost: 0.75 },
      { name: "Soy sauce", category: "pantry", quantity: "3 tbsp", cost: 0.30 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Sesame oil", category: "pantry", quantity: "1 tbsp", cost: 0.25 },
      { name: "Green onion", category: "produce", quantity: "2, sliced", cost: 0.40 },
    ],
    steps: [
      "Heat 1 tsp oil in a wok or large skillet over high heat. Beat eggs and scramble briefly. Set aside.",
      "Add another tablespoon oil; cook shrimp 2 minutes per side until pink. Set aside.",
      "Add garlic and frozen vegetables to the pan; cook 2 minutes.",
      "Add rice, breaking up clumps. Stir-fry 3-4 minutes until heated through and slightly crispy.",
      "Return eggs and shrimp to the pan; add soy sauce and sesame oil. Toss to combine.",
      "Garnish with green onion.",
    ],
  },
  {
    id: "19",
    name: "Mac And Cheese",
    image: IMG.macAndCheese,
    description: "Classic stovetop mac and cheese with a silky cheddar sauce.",
    prepTime: "5 min",
    cookTime: "15 min",
    tags: ["vegetarian", "comfort food", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 3,
    calories: 580,
    ingredients: [
      { name: "Elbow macaroni", category: "grains", quantity: "8 oz", cost: 1.00 },
      { name: "Butter", category: "dairy", quantity: "3 tbsp", cost: 0.45 },
      { name: "All-purpose flour", category: "pantry", quantity: "3 tbsp", cost: 0.10 },
      { name: "Milk", category: "dairy", quantity: "2 cups", cost: 1.00 },
      { name: "Sharp cheddar", category: "dairy", quantity: "2 cups shredded", cost: 3.00 },
      { name: "Salt & pepper", category: "spices", quantity: "to taste", cost: 0.05 },
      { name: "Smoked paprika", category: "spices", quantity: "1/4 tsp", cost: 0.10, optional: true },
    ],
    steps: [
      "Cook macaroni in salted boiling water until just shy of al dente. Drain.",
      "In the same pot, melt butter over medium heat. Whisk in flour and cook 1 minute (a roux).",
      "Slowly whisk in milk and bring to a gentle simmer until thickened, 3-4 minutes.",
      "Remove from heat and whisk in cheddar a handful at a time until smooth.",
      "Stir in pasta and season with salt, pepper, and paprika.",
    ],
  },
  {
    id: "20",
    name: "Avocado Toast",
    image: IMG.avocadoToast,
    description: "Sourdough piled with smashed avocado, lemon, and chili flakes.",
    prepTime: "5 min",
    tags: ["vegetarian", "quick", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 1,
    calories: 320,
    ingredients: [
      { name: "Sourdough bread", category: "grains", quantity: "2 slices", cost: 0.75 },
      { name: "Ripe avocado", category: "produce", quantity: "1", cost: 1.50 },
      { name: "Lemon juice", category: "produce", quantity: "1 tsp", cost: 0.10 },
      { name: "Red pepper flakes", category: "spices", quantity: "pinch", cost: 0.05 },
      { name: "Flaky sea salt", category: "spices", quantity: "to taste", cost: 0.05 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10, optional: true },
    ],
    steps: [
      "Toast sourdough until deeply golden and crisp.",
      "Halve the avocado, remove the pit, and scoop into a bowl.",
      "Add lemon juice and salt; mash with a fork to a chunky spread.",
      "Pile avocado generously onto toast.",
      "Top with chili flakes and a drizzle of olive oil.",
    ],
  },
  {
    id: "21",
    name: "Tuna Salad Sandwich",
    image: IMG.tunaSandwich,
    description: "Creamy tuna salad with celery and red onion on toasted bread.",
    prepTime: "10 min",
    tags: ["high protein", "quick", "lunch"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 430,
    ingredients: [
      { name: "Canned tuna (in water)", category: "protein", quantity: "1 can (5 oz), drained", cost: 1.75 },
      { name: "Mayonnaise", category: "pantry", quantity: "2 tbsp", cost: 0.30 },
      { name: "Celery", category: "produce", quantity: "1 stalk, diced", cost: 0.25 },
      { name: "Red onion", category: "produce", quantity: "1 tbsp, minced", cost: 0.15 },
      { name: "Dijon mustard", category: "pantry", quantity: "1 tsp", cost: 0.10 },
      { name: "Sandwich bread", category: "grains", quantity: "2 slices", cost: 0.50 },
      { name: "Lettuce", category: "produce", quantity: "1 leaf", cost: 0.20 },
    ],
    steps: [
      "Drain tuna very well and flake into a bowl.",
      "Add mayo, mustard, celery, and red onion. Mix until creamy. Season with salt and pepper.",
      "Toast bread.",
      "Lay lettuce on one slice, top with tuna mixture, close sandwich, and slice.",
    ],
  },
  {
    id: "22",
    name: "Breakfast Burrito",
    image: IMG.breakfastBurrito,
    description: "Scrambled eggs, sausage, and cheese rolled in a warm tortilla.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["high protein", "breakfast", "filling"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 1,
    calories: 620,
    ingredients: [
      { name: "Flour tortilla (large)", category: "grains", quantity: "1", cost: 0.50 },
      { name: "Eggs", category: "protein", quantity: "2", cost: 0.60 },
      { name: "Breakfast sausage", category: "protein", quantity: "2 links", cost: 1.50 },
      { name: "Shredded cheese", category: "dairy", quantity: "1/4 cup", cost: 0.60 },
      { name: "Bell pepper", category: "produce", quantity: "1/4, diced", cost: 0.35 },
      { name: "Salsa", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Butter", category: "dairy", quantity: "1 tsp", cost: 0.10 },
    ],
    steps: [
      "Brown sausage in a skillet until cooked through, breaking it up. Transfer to a plate.",
      "In the same pan, cook bell pepper 2 minutes until softened.",
      "Add butter, then beaten eggs; gently scramble until just set.",
      "Warm tortilla in a dry pan until pliable.",
      "Pile eggs, sausage, peppers, cheese, and salsa in the center of the tortilla.",
      "Fold sides in and roll tightly. Sear seam-side down 1 minute for a crisp finish.",
    ],
  },
  {
    id: "23",
    name: "Chicken Parmesan",
    image: IMG.chickenParm,
    description: "Breaded chicken cutlets baked with marinara and melty mozzarella.",
    prepTime: "15 min",
    cookTime: "25 min",
    tags: ["high protein", "comfort food", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 640,
    ingredients: [
      { name: "Chicken breast", category: "protein", quantity: "2 (pounded thin)", cost: 5.00 },
      { name: "Italian breadcrumbs", category: "pantry", quantity: "1 cup", cost: 0.75 },
      { name: "Egg", category: "protein", quantity: "1", cost: 0.30 },
      { name: "Marinara sauce", category: "pantry", quantity: "1 cup", cost: 1.50 },
      { name: "Mozzarella", category: "dairy", quantity: "1 cup shredded", cost: 2.00 },
      { name: "Parmesan", category: "dairy", quantity: "2 tbsp grated", cost: 0.50 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Preheat oven to 425°F (220°C).",
      "Beat egg in one shallow bowl; place breadcrumbs in another.",
      "Season chicken with salt and pepper. Dip in egg, then press into breadcrumbs.",
      "Heat olive oil in an oven-safe skillet; sear chicken 3 minutes per side until golden.",
      "Top each cutlet with marinara, mozzarella, and parmesan.",
      "Transfer skillet to oven; bake 12-15 minutes until cheese is bubbly and chicken is 165°F.",
    ],
  },
  {
    id: "24",
    name: "Veggie Burger",
    image: IMG.veggieBurger,
    description: "Black bean veggie patty on a brioche bun with all the fixings.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["vegetarian", "dinner", "comfort food"],
    difficulty: "Easy",
    category: "dinner",
    servings: 1,
    calories: 470,
    ingredients: [
      { name: "Frozen veggie burger patty", category: "protein", quantity: "1", cost: 2.50 },
      { name: "Brioche bun", category: "grains", quantity: "1", cost: 0.75 },
      { name: "Tomato", category: "produce", quantity: "2 slices", cost: 0.30 },
      { name: "Lettuce", category: "produce", quantity: "1 leaf", cost: 0.20 },
      { name: "Red onion", category: "produce", quantity: "2 thin rings", cost: 0.15 },
      { name: "Cheddar", category: "dairy", quantity: "1 slice", cost: 0.50 },
      { name: "Ketchup", category: "pantry", quantity: "1 tbsp", cost: 0.10 },
      { name: "Mayonnaise", category: "pantry", quantity: "1 tbsp", cost: 0.15 },
    ],
    steps: [
      "Cook veggie patty according to package directions (usually 4 minutes per side in a hot pan).",
      "In the last minute, top patty with cheese and cover to melt.",
      "Toast bun in the same pan for 30 seconds, cut side down.",
      "Spread mayo on top bun and ketchup on bottom bun.",
      "Stack lettuce, tomato, patty, and red onion. Close and serve.",
    ],
  },
  {
    id: "25",
    name: "Teriyaki Salmon",
    image: IMG.teriyakiSalmon,
    description: "Glazed salmon fillets with steamed rice and broccoli.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["high protein", "healthy", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 580,
    ingredients: [
      { name: "Salmon fillets", category: "protein", quantity: "2 (5 oz each)", cost: 9.00 },
      { name: "Teriyaki sauce", category: "pantry", quantity: "1/3 cup", cost: 0.75 },
      { name: "Honey", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
      { name: "White rice", category: "grains", quantity: "1 cup", cost: 0.50 },
      { name: "Broccoli", category: "produce", quantity: "2 cups florets", cost: 1.50 },
      { name: "Sesame seeds", category: "pantry", quantity: "1 tsp", cost: 0.15 },
      { name: "Green onion", category: "produce", quantity: "1, sliced", cost: 0.20 },
    ],
    steps: [
      "Cook rice according to package directions.",
      "Whisk teriyaki sauce with honey. Brush some over the salmon.",
      "Heat a non-stick skillet over medium-high. Sear salmon skin-side down 4 minutes.",
      "Flip salmon, brush with more glaze, and cook 3-4 minutes until it flakes easily.",
      "Steam broccoli for 4-5 minutes until tender-crisp.",
      "Plate rice, salmon, and broccoli. Drizzle remaining glaze, top with sesame seeds and green onion.",
    ],
  },
  {
    id: "26",
    name: "Pancakes",
    image: IMG.pancakes,
    description: "Fluffy buttermilk pancakes with butter and maple syrup.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["vegetarian", "comfort food", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 2,
    calories: 480,
    ingredients: [
      { name: "All-purpose flour", category: "pantry", quantity: "1 1/2 cups", cost: 0.30 },
      { name: "Sugar", category: "pantry", quantity: "2 tbsp", cost: 0.10 },
      { name: "Baking powder", category: "pantry", quantity: "2 tsp", cost: 0.10 },
      { name: "Salt", category: "spices", quantity: "1/2 tsp", cost: 0.05 },
      { name: "Buttermilk", category: "dairy", quantity: "1 1/4 cups", cost: 1.00 },
      { name: "Egg", category: "protein", quantity: "1", cost: 0.30 },
      { name: "Butter (melted)", category: "dairy", quantity: "3 tbsp", cost: 0.45 },
      { name: "Maple syrup", category: "pantry", quantity: "to serve", cost: 0.50 },
    ],
    steps: [
      "Whisk flour, sugar, baking powder, and salt in a bowl.",
      "In another bowl, whisk buttermilk, egg, and melted butter.",
      "Pour wet into dry and stir gently — lumps are okay, do not overmix.",
      "Heat a non-stick skillet over medium. Lightly grease.",
      "Pour 1/4 cup batter per pancake. Cook until bubbles form and edges set, about 2 minutes.",
      "Flip and cook 1-2 minutes more. Stack and serve with butter and syrup.",
    ],
  },
  {
    id: "27",
    name: "French Toast",
    image: IMG.frenchToast,
    description: "Custard-soaked bread fried in butter and dusted with sugar.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["vegetarian", "comfort food", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 2,
    calories: 420,
    ingredients: [
      { name: "Thick-cut bread (brioche or challah)", category: "grains", quantity: "4 slices", cost: 1.50 },
      { name: "Eggs", category: "protein", quantity: "3", cost: 0.90 },
      { name: "Milk", category: "dairy", quantity: "1/2 cup", cost: 0.30 },
      { name: "Sugar", category: "pantry", quantity: "1 tbsp", cost: 0.05 },
      { name: "Vanilla extract", category: "pantry", quantity: "1 tsp", cost: 0.20 },
      { name: "Cinnamon", category: "spices", quantity: "1/2 tsp", cost: 0.10 },
      { name: "Butter", category: "dairy", quantity: "2 tbsp", cost: 0.30 },
      { name: "Maple syrup", category: "pantry", quantity: "to serve", cost: 0.50 },
    ],
    steps: [
      "Whisk eggs, milk, sugar, vanilla, and cinnamon in a wide shallow dish.",
      "Dip each bread slice in custard, letting it soak about 20 seconds per side.",
      "Melt 1 tbsp butter in a non-stick skillet over medium heat.",
      "Cook bread 2-3 minutes per side until golden and set in the middle. Repeat with rest.",
      "Serve dusted with powdered sugar and drizzled with maple syrup.",
    ],
  },
  {
    id: "28",
    name: "Chicken Quesadilla",
    image: IMG.chickenQuesadilla,
    description: "Crispy tortilla layered with chicken, cheese, peppers, and onions.",
    prepTime: "10 min",
    cookTime: "8 min",
    tags: ["high protein", "quick", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 1,
    calories: 560,
    ingredients: [
      { name: "Cooked chicken (shredded)", category: "protein", quantity: "1 cup", cost: 3.00 },
      { name: "Flour tortilla (large)", category: "grains", quantity: "1", cost: 0.50 },
      { name: "Shredded cheese", category: "dairy", quantity: "1/2 cup", cost: 1.25 },
      { name: "Bell pepper", category: "produce", quantity: "1/4, sliced", cost: 0.35 },
      { name: "Red onion", category: "produce", quantity: "2 tbsp diced", cost: 0.15 },
      { name: "Olive oil", category: "pantry", quantity: "1 tsp", cost: 0.10 },
      { name: "Salsa", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Heat olive oil in a skillet over medium heat.",
      "Sauté pepper and onion 3 minutes until softened.",
      "Place tortilla in the pan. On half, layer cheese, chicken, peppers, onions, and more cheese.",
      "Fold tortilla in half and press down lightly.",
      "Cook 2-3 minutes until bottom is golden, then flip and cook 2 more minutes.",
      "Slice into wedges and serve with salsa.",
    ],
  },
  {
    id: "29",
    name: "Sweet Potato Bowl",
    image: IMG.sweetPotatoBowl,
    description: "Roasted sweet potato with quinoa, kale, chickpeas, and tahini.",
    prepTime: "10 min",
    cookTime: "25 min",
    tags: ["vegan", "healthy", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 530,
    ingredients: [
      { name: "Sweet potatoes", category: "produce", quantity: "2 medium, cubed", cost: 1.50 },
      { name: "Quinoa", category: "grains", quantity: "3/4 cup", cost: 1.25 },
      { name: "Kale", category: "produce", quantity: "2 cups, chopped", cost: 1.50 },
      { name: "Canned chickpeas", category: "pantry", quantity: "1 cup, drained", cost: 1.00 },
      { name: "Tahini", category: "pantry", quantity: "2 tbsp", cost: 0.50 },
      { name: "Lemon juice", category: "produce", quantity: "1 tbsp", cost: 0.20 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Cumin & paprika", category: "spices", quantity: "1 tsp each", cost: 0.20 },
    ],
    steps: [
      "Preheat oven to 425°F (220°C). Toss sweet potatoes and chickpeas with oil, cumin, paprika, salt.",
      "Spread on a sheet pan; roast 22-25 minutes, flipping halfway, until edges are crisp.",
      "Cook quinoa with 1 1/2 cups water in a covered pot for 15 minutes, then rest 5 minutes.",
      "Massage kale with a pinch of salt and a squeeze of lemon until softened.",
      "Whisk tahini with lemon juice and 1-2 tbsp water until pourable.",
      "Build bowls: quinoa, kale, sweet potato, chickpeas. Drizzle with tahini dressing.",
    ],
  },
  {
    id: "30",
    name: "Falafel Wrap",
    image: IMG.falafelWrap,
    description: "Crispy falafel with cucumber, tomato, and garlicky yogurt sauce.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["vegetarian", "lunch", "fresh"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 510,
    ingredients: [
      { name: "Frozen falafel", category: "protein", quantity: "5 pieces", cost: 2.00 },
      { name: "Pita or large flatbread", category: "grains", quantity: "1", cost: 0.75 },
      { name: "Cucumber", category: "produce", quantity: "1/2, diced", cost: 0.50 },
      { name: "Tomato", category: "produce", quantity: "1/2, diced", cost: 0.40 },
      { name: "Plain Greek yogurt", category: "dairy", quantity: "1/4 cup", cost: 0.50 },
      { name: "Lemon juice", category: "produce", quantity: "1 tsp", cost: 0.10 },
      { name: "Garlic", category: "produce", quantity: "1 clove, minced", cost: 0.05 },
      { name: "Lettuce", category: "produce", quantity: "1 handful", cost: 0.40 },
    ],
    steps: [
      "Cook falafel according to package (usually 10 min at 400°F or pan-fried in oil).",
      "Whisk yogurt, lemon juice, garlic, and a pinch of salt to make a quick sauce.",
      "Warm pita briefly so it's pliable.",
      "Smear yogurt sauce on the pita, then add lettuce, cucumber, tomato, and falafel.",
      "Roll up tightly, slice on the diagonal.",
    ],
  },
  {
    id: "31",
    name: "Pasta Primavera",
    image: IMG.pastaPrimavera,
    description: "Pasta tossed with seasonal vegetables, garlic, and parmesan.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["vegetarian", "healthy", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 470,
    ingredients: [
      { name: "Pasta (any short shape)", category: "grains", quantity: "200 g", cost: 1.00 },
      { name: "Zucchini", category: "produce", quantity: "1, sliced", cost: 0.75 },
      { name: "Bell pepper", category: "produce", quantity: "1, sliced", cost: 1.00 },
      { name: "Cherry tomatoes", category: "produce", quantity: "1 cup", cost: 1.50 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Olive oil", category: "pantry", quantity: "3 tbsp", cost: 0.60 },
      { name: "Parmesan", category: "dairy", quantity: "1/4 cup", cost: 1.00 },
      { name: "Lemon zest", category: "produce", quantity: "1 tsp", cost: 0.15 },
    ],
    steps: [
      "Bring salted water to a boil; cook pasta until al dente. Reserve 1/2 cup water; drain.",
      "Heat olive oil in a large skillet over medium-high heat. Sauté garlic 30 seconds.",
      "Add bell pepper and zucchini; cook 4-5 minutes until tender.",
      "Add tomatoes and cook 2 minutes more until they begin to burst.",
      "Toss in pasta, a splash of pasta water, and parmesan. Stir to glaze.",
      "Finish with lemon zest and a crack of pepper.",
    ],
  },
  {
    id: "32",
    name: "Pork Chops With Apple",
    image: IMG.porkChops,
    description: "Pan-seared pork chops with caramelized apples and onions.",
    prepTime: "10 min",
    cookTime: "20 min",
    tags: ["high protein", "comfort food", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 550,
    ingredients: [
      { name: "Bone-in pork chops", category: "protein", quantity: "2", cost: 7.00 },
      { name: "Apple (Honeycrisp or Gala)", category: "produce", quantity: "1, sliced", cost: 0.85 },
      { name: "Yellow onion", category: "produce", quantity: "1/2, sliced", cost: 0.30 },
      { name: "Butter", category: "dairy", quantity: "2 tbsp", cost: 0.30 },
      { name: "Apple cider", category: "pantry", quantity: "1/2 cup", cost: 0.75 },
      { name: "Fresh thyme", category: "produce", quantity: "2 sprigs", cost: 0.50 },
      { name: "Olive oil", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
    ],
    steps: [
      "Pat chops dry; season generously with salt and pepper.",
      "Heat olive oil in a skillet over medium-high. Sear chops 4 minutes per side until 145°F. Rest.",
      "Lower heat; melt butter in the same pan. Add onion, cook 4 minutes.",
      "Add apple slices and thyme; cook 3 minutes until softened.",
      "Pour in cider, scraping up brown bits; simmer 3 minutes until syrupy.",
      "Return chops and any resting juices to the pan, spoon sauce over, and serve.",
    ],
  },
  {
    id: "33",
    name: "Chicken Caesar Salad",
    image: IMG.caesarSalad,
    description: "Crisp romaine with grilled chicken, parmesan, and caesar dressing.",
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["high protein", "lunch", "fresh"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 480,
    ingredients: [
      { name: "Chicken breast", category: "protein", quantity: "1", cost: 2.50 },
      { name: "Romaine lettuce", category: "produce", quantity: "1 head, chopped", cost: 2.00 },
      { name: "Caesar dressing", category: "pantry", quantity: "3 tbsp", cost: 0.75 },
      { name: "Parmesan", category: "dairy", quantity: "3 tbsp grated", cost: 0.75 },
      { name: "Croutons", category: "grains", quantity: "1/2 cup", cost: 0.50 },
      { name: "Lemon juice", category: "produce", quantity: "1 tsp", cost: 0.10 },
      { name: "Olive oil", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
    ],
    steps: [
      "Season chicken with salt and pepper.",
      "Heat olive oil in a skillet over medium-high; cook chicken 5-6 minutes per side (165°F).",
      "Rest 5 minutes, then slice on the diagonal.",
      "Toss romaine with dressing, lemon juice, and most of the parmesan.",
      "Plate salad, top with chicken, croutons, and remaining parmesan.",
    ],
  },
  {
    id: "34",
    name: "Steak Fajitas",
    image: IMG.steakFajitas,
    description: "Sizzling skirt steak with bell peppers and onions for warm tortillas.",
    prepTime: "15 min",
    cookTime: "15 min",
    tags: ["high protein", "dinner", "spicy"],
    difficulty: "Medium",
    category: "dinner",
    servings: 3,
    calories: 580,
    ingredients: [
      { name: "Skirt or flank steak", category: "protein", quantity: "1 lb", cost: 9.00 },
      { name: "Bell peppers (assorted)", category: "produce", quantity: "2, sliced", cost: 2.00 },
      { name: "Yellow onion", category: "produce", quantity: "1, sliced", cost: 0.50 },
      { name: "Lime", category: "produce", quantity: "1", cost: 0.40 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Fajita seasoning (cumin, paprika, chili)", category: "spices", quantity: "1 tbsp", cost: 0.30 },
      { name: "Flour tortillas", category: "grains", quantity: "6 small", cost: 1.25 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Toss steak with half the seasoning, half the lime juice, and 1 tbsp oil. Marinate 10 minutes.",
      "Heat remaining oil in a large skillet over high heat. Sear steak 3-4 minutes per side. Rest.",
      "In the same pan, add peppers, onion, garlic, and remaining seasoning. Stir-fry 5-6 minutes.",
      "Slice steak thinly against the grain.",
      "Warm tortillas. Serve steak and peppers with lime wedges and tortillas.",
    ],
  },
  {
    id: "35",
    name: "Vegetable Curry",
    image: IMG.vegCurry,
    description: "Coconut curry with cauliflower, potato, and chickpeas over rice.",
    prepTime: "10 min",
    cookTime: "25 min",
    tags: ["vegan", "comfort food", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 3,
    calories: 490,
    ingredients: [
      { name: "Cauliflower", category: "produce", quantity: "1/2 head, florets", cost: 1.50 },
      { name: "Yukon gold potato", category: "produce", quantity: "1 large, cubed", cost: 0.75 },
      { name: "Canned chickpeas", category: "pantry", quantity: "1 can, drained", cost: 1.00 },
      { name: "Coconut milk", category: "pantry", quantity: "1 can (14 oz)", cost: 2.00 },
      { name: "Curry paste (red or yellow)", category: "pantry", quantity: "3 tbsp", cost: 1.50 },
      { name: "Yellow onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Cooked basmati rice", category: "grains", quantity: "3 cups, to serve", cost: 1.00 },
    ],
    steps: [
      "Heat oil in a deep pan; cook onion 4 minutes until soft. Add garlic and curry paste; cook 1 minute.",
      "Add coconut milk and 1/2 cup water; bring to a simmer.",
      "Add potato; simmer 8 minutes.",
      "Add cauliflower and chickpeas; simmer another 10-12 minutes until vegetables are tender.",
      "Season with salt and a squeeze of lime if you have it.",
      "Spoon over rice and serve.",
    ],
  },
  {
    id: "36",
    name: "Tomato Basil Soup",
    image: IMG.tomatoSoup,
    description: "Silky blended tomato soup with fresh basil — pairs perfectly with grilled cheese.",
    prepTime: "5 min",
    cookTime: "25 min",
    tags: ["vegetarian", "comfort food", "lunch"],
    difficulty: "Easy",
    category: "lunch",
    servings: 4,
    calories: 240,
    ingredients: [
      { name: "Canned San Marzano tomatoes", category: "pantry", quantity: "2 cans (28 oz)", cost: 5.00 },
      { name: "Yellow onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Fresh basil", category: "produce", quantity: "1/2 cup leaves", cost: 1.00 },
      { name: "Heavy cream", category: "dairy", quantity: "1/4 cup", cost: 0.75 },
      { name: "Butter", category: "dairy", quantity: "2 tbsp", cost: 0.30 },
      { name: "Vegetable broth", category: "pantry", quantity: "1 cup", cost: 0.50 },
    ],
    steps: [
      "Melt butter in a pot; cook onion 5 minutes until translucent.",
      "Add garlic; cook 30 seconds.",
      "Add tomatoes (crushing with your hands) and broth. Simmer 20 minutes.",
      "Stir in most of the basil. Blend smooth with an immersion blender (or carefully in batches).",
      "Stir in cream, taste, and season with salt, pepper, and a pinch of sugar if too acidic.",
      "Serve topped with remaining basil leaves.",
    ],
  },
  {
    id: "37",
    name: "Grilled Cheese",
    image: IMG.grilledCheese,
    description: "Golden, buttery sourdough hugging melty cheddar and gruyère.",
    prepTime: "5 min",
    cookTime: "6 min",
    tags: ["vegetarian", "comfort food", "lunch"],
    difficulty: "Easy",
    category: "lunch",
    servings: 1,
    calories: 540,
    ingredients: [
      { name: "Sourdough bread", category: "grains", quantity: "2 thick slices", cost: 0.80 },
      { name: "Sharp cheddar", category: "dairy", quantity: "1 slice", cost: 0.75 },
      { name: "Gruyère", category: "dairy", quantity: "1 slice", cost: 1.25 },
      { name: "Butter", category: "dairy", quantity: "2 tbsp", cost: 0.30 },
      { name: "Dijon mustard", category: "pantry", quantity: "1 tsp", cost: 0.10, optional: true },
    ],
    steps: [
      "Butter the outside of each bread slice.",
      "Spread a thin layer of dijon on the inside of one slice if using.",
      "Layer cheese between the slices, butter-side out.",
      "Cook in a skillet over medium-low heat 3 minutes per side, pressing gently, until golden and melted through.",
      "Rest 1 minute, then cut diagonally.",
    ],
  },
  {
    id: "38",
    name: "Eggplant Parmesan",
    image: IMG.eggplantParm,
    description: "Layers of crispy eggplant, marinara, and mozzarella, baked till bubbly.",
    prepTime: "20 min",
    cookTime: "35 min",
    tags: ["vegetarian", "comfort food", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 4,
    calories: 520,
    ingredients: [
      { name: "Eggplant", category: "produce", quantity: "2 medium, sliced 1/2-inch", cost: 3.00 },
      { name: "Italian breadcrumbs", category: "pantry", quantity: "1 1/2 cups", cost: 1.00 },
      { name: "Eggs", category: "protein", quantity: "2", cost: 0.60 },
      { name: "Marinara sauce", category: "pantry", quantity: "2 1/2 cups", cost: 3.00 },
      { name: "Mozzarella", category: "dairy", quantity: "2 cups shredded", cost: 4.00 },
      { name: "Parmesan", category: "dairy", quantity: "1/2 cup", cost: 1.50 },
      { name: "Olive oil", category: "pantry", quantity: "1/4 cup", cost: 0.75 },
    ],
    steps: [
      "Salt eggplant slices; rest 15 minutes to draw out moisture. Pat dry.",
      "Preheat oven to 400°F. Beat eggs; place breadcrumbs in a second dish.",
      "Dip eggplant in egg, then breadcrumbs. Place on oiled sheet pans.",
      "Roast 20 minutes, flipping halfway, until golden.",
      "Layer in a baking dish: sauce, eggplant, sauce, mozzarella, parmesan; repeat.",
      "Bake 15 minutes more until bubbly. Rest 5 minutes before serving.",
    ],
  },
  {
    id: "39",
    name: "Chicken Tikka Masala",
    image: IMG.tikkaMasala,
    description: "Tender chicken in a rich, spiced tomato-cream sauce served over rice.",
    prepTime: "20 min",
    cookTime: "25 min",
    tags: ["high protein", "spicy", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 3,
    calories: 620,
    ingredients: [
      { name: "Boneless chicken thighs", category: "protein", quantity: "1 lb, cubed", cost: 6.00 },
      { name: "Plain Greek yogurt", category: "dairy", quantity: "1/2 cup", cost: 0.75 },
      { name: "Garam masala", category: "spices", quantity: "2 tsp", cost: 0.30 },
      { name: "Tomato puree", category: "pantry", quantity: "1 1/2 cups", cost: 1.50 },
      { name: "Heavy cream", category: "dairy", quantity: "1/2 cup", cost: 1.00 },
      { name: "Onion", category: "produce", quantity: "1, finely diced", cost: 0.50 },
      { name: "Garlic & ginger paste", category: "produce", quantity: "2 tbsp", cost: 0.50 },
      { name: "Basmati rice", category: "grains", quantity: "1 1/2 cups, cooked", cost: 1.00 },
    ],
    steps: [
      "Marinate chicken in yogurt and 1 tsp garam masala for 15-30 minutes.",
      "Sear chicken in a hot oiled pan until browned on all sides. Remove.",
      "In the same pan, cook onion 4 minutes until soft. Add garlic-ginger; cook 1 minute.",
      "Stir in remaining garam masala, then tomato puree. Simmer 8 minutes until darkened.",
      "Stir in cream and chicken; simmer 8-10 minutes until chicken is cooked through (165°F).",
      "Serve over basmati rice with a sprinkle of cilantro.",
    ],
  },
  {
    id: "40",
    name: "Beef Stir Fry",
    image: IMG.beefStirFry,
    description: "Quick stir-fried beef with broccoli and a savory garlic-ginger sauce.",
    prepTime: "15 min",
    cookTime: "10 min",
    tags: ["high protein", "quick", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 540,
    ingredients: [
      { name: "Flank steak", category: "protein", quantity: "3/4 lb, thinly sliced", cost: 7.00 },
      { name: "Broccoli florets", category: "produce", quantity: "3 cups", cost: 2.00 },
      { name: "Soy sauce", category: "pantry", quantity: "3 tbsp", cost: 0.30 },
      { name: "Oyster sauce", category: "pantry", quantity: "1 tbsp", cost: 0.30 },
      { name: "Cornstarch", category: "pantry", quantity: "1 tbsp", cost: 0.10 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Fresh ginger", category: "produce", quantity: "1 tbsp grated", cost: 0.30 },
      { name: "Cooked rice", category: "grains", quantity: "2 cups, to serve", cost: 0.75 },
    ],
    steps: [
      "Toss beef with 1 tbsp soy sauce and cornstarch; rest 10 minutes.",
      "Blanch broccoli in boiling water 90 seconds, drain.",
      "Heat oil in a hot wok or skillet. Sear beef in a single layer 1 minute per side. Remove.",
      "Add garlic and ginger to pan; stir-fry 30 seconds.",
      "Return beef with broccoli, remaining soy sauce, and oyster sauce; toss 1-2 minutes.",
      "Serve over rice.",
    ],
  },
  {
    id: "41",
    name: "Shrimp Scampi",
    image: IMG.shrimpScampi,
    description: "Buttery garlic shrimp tossed with pasta, white wine, and lemon.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["high protein", "dinner", "comfort food"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 560,
    ingredients: [
      { name: "Linguine", category: "grains", quantity: "8 oz", cost: 1.25 },
      { name: "Large shrimp (peeled)", category: "protein", quantity: "1 lb", cost: 9.00 },
      { name: "Butter", category: "dairy", quantity: "4 tbsp", cost: 0.60 },
      { name: "Garlic", category: "produce", quantity: "5 cloves, sliced", cost: 0.25 },
      { name: "White wine", category: "pantry", quantity: "1/2 cup", cost: 1.00 },
      { name: "Lemon", category: "produce", quantity: "1, juiced and zested", cost: 0.50 },
      { name: "Fresh parsley", category: "produce", quantity: "2 tbsp chopped", cost: 0.50 },
      { name: "Red pepper flakes", category: "spices", quantity: "1/4 tsp", cost: 0.05 },
    ],
    steps: [
      "Cook linguine in salted water until al dente. Reserve 1/2 cup pasta water; drain.",
      "Melt 2 tbsp butter in a large skillet over medium heat. Add garlic and pepper flakes; cook 30 seconds.",
      "Add shrimp in a single layer. Cook 1-2 minutes per side until pink. Remove.",
      "Add wine and lemon juice; simmer until reduced by half.",
      "Whisk in remaining butter, then return shrimp and pasta; add splash of pasta water.",
      "Toss with parsley and lemon zest; serve immediately.",
    ],
  },
  {
    id: "42",
    name: "Baked Ziti",
    image: IMG.bakedZiti,
    description: "Pasta baked with marinara, ricotta, and stretchy mozzarella.",
    prepTime: "15 min",
    cookTime: "30 min",
    tags: ["vegetarian", "comfort food", "dinner"],
    difficulty: "Easy",
    category: "dinner",
    servings: 4,
    calories: 620,
    ingredients: [
      { name: "Ziti or penne", category: "grains", quantity: "1 lb", cost: 1.50 },
      { name: "Marinara sauce", category: "pantry", quantity: "24 oz jar", cost: 3.00 },
      { name: "Ricotta", category: "dairy", quantity: "15 oz", cost: 3.50 },
      { name: "Mozzarella", category: "dairy", quantity: "2 cups shredded", cost: 4.00 },
      { name: "Parmesan", category: "dairy", quantity: "1/4 cup", cost: 1.00 },
      { name: "Egg", category: "protein", quantity: "1", cost: 0.30 },
      { name: "Italian seasoning", category: "spices", quantity: "1 tsp", cost: 0.10 },
      { name: "Fresh basil", category: "produce", quantity: "for serving", cost: 0.50, optional: true },
    ],
    steps: [
      "Preheat oven to 375°F. Cook pasta in salted water 2 minutes shy of al dente; drain.",
      "Mix ricotta with egg, parmesan, Italian seasoning, salt, and pepper.",
      "Toss pasta with marinara.",
      "In a baking dish, layer half the pasta, dollops of ricotta, half the mozzarella; repeat.",
      "Bake covered 15 minutes, then uncover and bake 12-15 more minutes until bubbly.",
      "Top with basil if using.",
    ],
  },
  {
    id: "43",
    name: "Chicken Noodle Soup",
    image: IMG.chickenNoodleSoup,
    description: "Comforting broth with shredded chicken, egg noodles, and vegetables.",
    prepTime: "10 min",
    cookTime: "25 min",
    tags: ["comfort food", "lunch", "healthy"],
    difficulty: "Easy",
    category: "lunch",
    servings: 4,
    calories: 340,
    ingredients: [
      { name: "Boneless chicken breast", category: "protein", quantity: "1/2 lb", cost: 3.00 },
      { name: "Egg noodles", category: "grains", quantity: "6 oz", cost: 1.00 },
      { name: "Chicken broth", category: "pantry", quantity: "8 cups", cost: 3.00 },
      { name: "Carrots", category: "produce", quantity: "2, sliced", cost: 0.50 },
      { name: "Celery", category: "produce", quantity: "2 stalks, sliced", cost: 0.50 },
      { name: "Onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Garlic", category: "produce", quantity: "2 cloves", cost: 0.10 },
      { name: "Fresh parsley & dill", category: "produce", quantity: "2 tbsp chopped", cost: 0.50 },
    ],
    steps: [
      "Sauté onion, carrot, and celery in a soup pot with oil 6 minutes until soft. Add garlic 30 seconds.",
      "Add broth; bring to a simmer. Slip in whole chicken breasts; poach 12-14 minutes.",
      "Remove chicken; shred with two forks.",
      "Add noodles to the simmering broth and cook per package directions, about 6 minutes.",
      "Return chicken; season with salt and pepper.",
      "Stir in herbs just before serving.",
    ],
  },
  {
    id: "44",
    name: "Spinach Quiche",
    image: IMG.spinachQuiche,
    description: "Buttery crust filled with eggs, cheese, and sautéed spinach.",
    prepTime: "15 min",
    cookTime: "40 min",
    tags: ["vegetarian", "breakfast", "make-ahead"],
    difficulty: "Medium",
    category: "breakfast",
    servings: 6,
    calories: 380,
    ingredients: [
      { name: "Pre-made pie crust", category: "grains", quantity: "1", cost: 3.00 },
      { name: "Eggs", category: "protein", quantity: "4 large", cost: 1.20 },
      { name: "Milk", category: "dairy", quantity: "1 cup", cost: 0.50 },
      { name: "Heavy cream", category: "dairy", quantity: "1/2 cup", cost: 1.00 },
      { name: "Fresh spinach", category: "produce", quantity: "5 oz", cost: 2.00 },
      { name: "Gruyère or swiss", category: "dairy", quantity: "1 cup shredded", cost: 2.50 },
      { name: "Yellow onion", category: "produce", quantity: "1/2, diced", cost: 0.25 },
      { name: "Nutmeg", category: "spices", quantity: "pinch", cost: 0.05 },
    ],
    steps: [
      "Preheat oven to 375°F. Press pie crust into a 9-inch pie dish; chill while you cook the filling.",
      "Sauté onion 4 minutes; add spinach and cook until wilted. Cool slightly.",
      "Whisk eggs, milk, cream, salt, pepper, and nutmeg.",
      "Spread spinach-onion mixture and cheese in crust.",
      "Pour custard over the top.",
      "Bake 35-40 minutes until just set in the center. Rest 10 minutes before slicing.",
    ],
  },
  {
    id: "45",
    name: "Stuffed Bell Peppers",
    image: IMG.stuffedPeppers,
    description: "Bell peppers stuffed with seasoned ground beef, rice, and tomato.",
    prepTime: "15 min",
    cookTime: "40 min",
    tags: ["high protein", "dinner", "make-ahead"],
    difficulty: "Medium",
    category: "dinner",
    servings: 4,
    calories: 480,
    ingredients: [
      { name: "Bell peppers", category: "produce", quantity: "4 large", cost: 4.00 },
      { name: "Ground beef", category: "protein", quantity: "1 lb", cost: 5.50 },
      { name: "Cooked rice", category: "grains", quantity: "1 1/2 cups", cost: 1.00 },
      { name: "Canned diced tomatoes", category: "pantry", quantity: "1 can (14 oz)", cost: 1.25 },
      { name: "Onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Garlic", category: "produce", quantity: "2 cloves", cost: 0.10 },
      { name: "Italian seasoning", category: "spices", quantity: "1 tsp", cost: 0.10 },
      { name: "Mozzarella", category: "dairy", quantity: "1 cup shredded", cost: 2.00 },
    ],
    steps: [
      "Preheat oven to 375°F. Cut tops off peppers and remove seeds; place upright in a baking dish.",
      "Brown beef in a skillet, breaking it up. Drain excess fat.",
      "Add onion and garlic, cook 4 minutes. Stir in tomatoes, rice, Italian seasoning, salt, and pepper.",
      "Spoon mixture into peppers and top with cheese.",
      "Add 1/4 cup water to dish; cover with foil and bake 30 minutes.",
      "Uncover and bake 10 minutes more until peppers are tender and cheese is golden.",
    ],
  },
  {
    id: "46",
    name: "Chicken Fajita Bowl",
    image: IMG.chickenFajitaBowl,
    description: "Cilantro lime rice with fajita-spiced chicken, peppers, and black beans.",
    prepTime: "10 min",
    cookTime: "15 min",
    tags: ["high protein", "dinner", "healthy"],
    difficulty: "Easy",
    category: "dinner",
    servings: 2,
    calories: 580,
    ingredients: [
      { name: "Chicken breast", category: "protein", quantity: "1 lb, sliced", cost: 5.00 },
      { name: "Bell peppers", category: "produce", quantity: "2, sliced", cost: 2.00 },
      { name: "Onion", category: "produce", quantity: "1, sliced", cost: 0.50 },
      { name: "Canned black beans", category: "pantry", quantity: "1 cup, rinsed", cost: 0.75 },
      { name: "Cooked rice", category: "grains", quantity: "2 cups", cost: 0.75 },
      { name: "Fajita seasoning", category: "spices", quantity: "1 tbsp", cost: 0.30 },
      { name: "Lime", category: "produce", quantity: "1", cost: 0.40 },
      { name: "Fresh cilantro", category: "produce", quantity: "2 tbsp chopped", cost: 0.50 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Toss chicken with fajita seasoning and 1 tbsp oil.",
      "Heat remaining oil in a large skillet over medium-high. Cook chicken 5-7 minutes until golden. Remove.",
      "Add peppers and onion to the same pan; cook 5 minutes until charred at the edges.",
      "Warm black beans in the microwave or in a small pan.",
      "Stir lime juice and cilantro into the rice.",
      "Build bowls: cilantro-lime rice, chicken, peppers, beans, and a lime wedge.",
    ],
  },
  {
    id: "47",
    name: "Tofu Scramble",
    image: IMG.tofuScramble,
    description: "Eggy-style scramble made from crumbled tofu with turmeric and veggies.",
    prepTime: "5 min",
    cookTime: "10 min",
    tags: ["vegan", "high protein", "breakfast"],
    difficulty: "Easy",
    category: "breakfast",
    servings: 2,
    calories: 290,
    ingredients: [
      { name: "Firm tofu", category: "protein", quantity: "1 block (14 oz)", cost: 2.50 },
      { name: "Turmeric", category: "spices", quantity: "1/2 tsp", cost: 0.15 },
      { name: "Nutritional yeast", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Bell pepper", category: "produce", quantity: "1/2, diced", cost: 0.50 },
      { name: "Spinach", category: "produce", quantity: "1 cup", cost: 0.50 },
      { name: "Garlic powder", category: "spices", quantity: "1/2 tsp", cost: 0.10 },
      { name: "Olive oil", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
      { name: "Salt & pepper", category: "spices", quantity: "to taste", cost: 0.05 },
    ],
    steps: [
      "Drain tofu and crumble it into bite-sized pieces with your hands.",
      "Heat oil in a skillet over medium heat. Add bell pepper; cook 3 minutes.",
      "Add tofu, turmeric, garlic powder, salt, and pepper. Cook 5 minutes, stirring occasionally.",
      "Stir in nutritional yeast and spinach; cook 1-2 minutes until spinach wilts.",
      "Taste and adjust seasoning; serve hot.",
    ],
  },
  {
    id: "48",
    name: "Fish Tacos",
    image: IMG.fishTacos,
    description: "Crispy fish in warm tortillas with cabbage slaw and chipotle crema.",
    prepTime: "15 min",
    cookTime: "10 min",
    tags: ["high protein", "fresh", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 540,
    ingredients: [
      { name: "White fish fillets (cod or tilapia)", category: "protein", quantity: "1 lb", cost: 7.00 },
      { name: "Corn tortillas", category: "grains", quantity: "6 small", cost: 1.00 },
      { name: "Shredded cabbage", category: "produce", quantity: "2 cups", cost: 1.25 },
      { name: "Lime", category: "produce", quantity: "1", cost: 0.40 },
      { name: "Sour cream", category: "dairy", quantity: "1/3 cup", cost: 0.75 },
      { name: "Chipotle in adobo", category: "pantry", quantity: "1 tsp, minced", cost: 0.30 },
      { name: "Chili powder", category: "spices", quantity: "1 tsp", cost: 0.10 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Cilantro", category: "produce", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Pat fish dry. Season with chili powder, salt, and pepper.",
      "Whisk sour cream with chipotle and a squeeze of lime; set aside.",
      "Toss cabbage with lime juice, cilantro, and a pinch of salt.",
      "Heat oil in a skillet over medium-high. Cook fish 3 minutes per side until flaky.",
      "Warm tortillas in a dry pan.",
      "Flake fish into tortillas; top with slaw and chipotle crema.",
    ],
  },
  {
    id: "49",
    name: "Beef Stew",
    image: IMG.beefStew,
    description: "Slow-simmered beef chuck with potatoes, carrots, and rich gravy.",
    prepTime: "20 min",
    cookTime: "120 min",
    tags: ["comfort food", "dinner", "make-ahead"],
    difficulty: "Medium",
    category: "dinner",
    servings: 4,
    calories: 580,
    ingredients: [
      { name: "Beef chuck", category: "protein", quantity: "1 1/2 lb, cubed", cost: 12.00 },
      { name: "Yukon gold potatoes", category: "produce", quantity: "1 lb, cubed", cost: 2.00 },
      { name: "Carrots", category: "produce", quantity: "3, chunks", cost: 0.75 },
      { name: "Yellow onion", category: "produce", quantity: "1, diced", cost: 0.50 },
      { name: "Beef broth", category: "pantry", quantity: "4 cups", cost: 1.75 },
      { name: "Tomato paste", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
      { name: "Flour", category: "pantry", quantity: "3 tbsp", cost: 0.10 },
      { name: "Fresh thyme & bay leaf", category: "produce", quantity: "few sprigs / 1 leaf", cost: 0.75 },
      { name: "Olive oil", category: "pantry", quantity: "2 tbsp", cost: 0.40 },
    ],
    steps: [
      "Pat beef dry, season with salt and pepper, toss with flour.",
      "Heat oil in a Dutch oven; brown beef in batches, about 3 minutes per side. Remove.",
      "Add onion; cook 5 minutes. Stir in tomato paste; cook 1 minute.",
      "Return beef and add broth, thyme, and bay. Simmer covered on low 90 minutes.",
      "Add potatoes and carrots; simmer uncovered 25-30 minutes until vegetables are tender and broth has reduced.",
      "Discard herbs, season to taste, and serve.",
    ],
  },
  {
    id: "50",
    name: "Chicken Alfredo",
    image: IMG.chickenAlfredo,
    description: "Tender chicken over fettuccine in a rich parmesan cream sauce.",
    prepTime: "10 min",
    cookTime: "20 min",
    tags: ["high protein", "comfort food", "dinner"],
    difficulty: "Medium",
    category: "dinner",
    servings: 2,
    calories: 720,
    ingredients: [
      { name: "Fettuccine", category: "grains", quantity: "8 oz", cost: 1.25 },
      { name: "Chicken breast", category: "protein", quantity: "1 large", cost: 3.00 },
      { name: "Heavy cream", category: "dairy", quantity: "1 cup", cost: 2.00 },
      { name: "Butter", category: "dairy", quantity: "3 tbsp", cost: 0.45 },
      { name: "Parmesan", category: "dairy", quantity: "1 cup grated", cost: 2.50 },
      { name: "Garlic", category: "produce", quantity: "3 cloves", cost: 0.15 },
      { name: "Olive oil", category: "pantry", quantity: "1 tbsp", cost: 0.20 },
      { name: "Fresh parsley", category: "produce", quantity: "1 tbsp", cost: 0.30, optional: true },
    ],
    steps: [
      "Season chicken with salt and pepper. Sear in olive oil, 5-6 minutes per side. Rest, then slice.",
      "Cook fettuccine in salted water until al dente. Reserve 1/2 cup pasta water; drain.",
      "In the same pasta pot, melt butter and cook garlic 30 seconds.",
      "Add cream; simmer 2-3 minutes until slightly thickened.",
      "Off heat, whisk in parmesan a handful at a time until silky. Loosen with pasta water if needed.",
      "Toss pasta with sauce and top with sliced chicken and parsley.",
    ],
  },
];

// ---------------------------------------------------------------------------
// Build the exported recipe list, computing cost from ingredients so the
// "Cost" badge always matches the sum on the grocery list.
// ---------------------------------------------------------------------------
function hydrate(seed: RecipeSeed, index: number): Recipe {
  // Spread the creation timestamps across a couple of weeks so the "recent"
  // and "popular" helpers stay sensible.
  const day = 10 + Math.floor(index / 3);
  const hour = 8 + (index % 8);
  const created = new Date(`2025-01-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:00:00`);
  return {
    ...seed,
    cost: totalCost(seed.ingredients),
    createdAt: created,
    updatedAt: created,
    source: "system",
    isPublic: true,
    timesCooked: 0,
  };
}

export const ALL_SEED_RECIPES: Recipe[] = SEEDS.map(hydrate);

// Kept for backward compatibility — same content as ALL_SEED_RECIPES now.
export const SEED_RECIPES: Recipe[] = ALL_SEED_RECIPES;
